name: Trigger-WF-OWASP-Workflow

on: workflow_dispatch

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="aszpilkowski"
          repo_name="wf-gha"
          event_type="wf-core-owasp-trigger"
          echo ${{ secrets.GITHUB_TOKEN }}
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"wf-gha\", \"version\": \"1.0-SNAPSHOT-PSI\"\"unit\": false, \"integration\": true}}"
