name: WF Cron Test Reusable Workflow

on:
  schedule:
    - cron: '40 10 * * *'

jobs: 
  wf_core_main:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: "main"
          ref: main
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/main/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn clean install --file ${{ github.workspace }}/main/pom.xml

      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: dependency-check-wf-core-main
        with:
          project: 'wf-core-gha'
          path: '.'
          format: 'ALL'
          out: 'reports/main'
          args: >
            --enableRetired
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            -s "${{ github.workspace }}/main/**"

  wf_core_26:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: "wf_26"
          ref: main
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/wf_26/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn clean install --file ${{ github.workspace }}/wf_26/pom.xml

      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: dependency-check-wf-core-26
        with:
          project: 'wf-core-gha'
          path: '.'
          format: 'ALL'
          out: 'reports/wf_26'
          args: >
            --enableRetired
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            -s "${{ github.workspace }}/wf_26/**"
    
  wf_core_31:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: "wf_31"
          ref: main
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/wf_31/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn clean install --file ${{ github.workspace }}/wf_31/pom.xml

      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: dependency-check-wf-core-31
        with:
          project: 'wf-core-gha'
          path: '.'
          format: 'ALL'
          out: 'reports/wf_31'
          args: >
            --enableRetired
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            -s "${{ github.workspace }}/wf_31/**"

  upload_reports:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [wf_core_main, wf_core_26, wf_core_31]
    steps:
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: dependency-check-report-main
          path: ${{github.workspace}}/reports

  run_wf_workflow:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [ upload_reports ]
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="aszpilkowski"
          repo_name="wf-gha"
          event_type="wf-core-owasp-trigger"
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_KEY }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"run_id\": \"${{ github.run_id }}\", \"service\": \"wf-gha\", \"version\": \"1.0-SNAPSHOT-PSI\", \"unit\": false, \"integration\": true}}"
  
