name: WF Cron Test Reusable Workflow

on:
  schedule:
    - cron: '55 9 * * *'

jobs:
  wf_21:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/wf_26' # Replace branch1 and branch2 with your specific branches
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
          ref: 'wf_26'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      # Add your job steps here
