name: WF Cron Test Reusable Workflow

on:
  schedule:
    - cron: '45 10 * * *'

jobs:
  wf_21:
    uses: aszpilkowski/wf-core-gha/.github/workflows/remote_trigger_OWASP.yml@main
  wf_26:
    uses: aszpilkowski/wf-core-gha/.github/workflows/remote_trigger_OWASP.yml@wf_26
  wf_31:
    uses: aszpilkowski/wf-core-gha/.github/workflows/remote_trigger_OWASP.yml@wf_31
