name: WF Cron Test Reusable Workflow

on: workflow_dispatch

jobs:
  cron_job_main:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/main' || ${{ github.ref }} == 'refs/heads/wf_26'
    
    steps:
      - name: echo ref
        run: echo ${{ github.ref }}
      - uses: ./.github/workflows/wf-core-main-action.yml@main

