name: WF Cron Test Reusable Workflow

on:
  schedule:
    - cron: '45 12 * * *'

jobs:
  wf_21:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/main' || ${{ github.ref }} == 'refs/heads/wf_26'
    
    steps:
      - name: echo ref
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'pom.xml' # optional
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
        
      # Add your job steps here
