name: WF Cron Test Reusable Workflow

on:
  schedule:
    - cron: '30 7 * * *'

jobs:
  cron_job_main:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo github repository
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn clean install --file pom.xml

  cron_job_wf_26:
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo github repository
        run: echo ${{ github.ref }}
      - uses: actions/checkout@v4
        with:
          ref: wf_26
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn clean install --file pom.xml
